"""Изменил значение по умолчанию для поля avatar модели UserModel

Revision ID: 2af7c02b56d5
Revises: 34a844edd2d1
Create Date: 2026-03-04 18:58:08.419605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af7c02b56d5'
down_revision: Union[str, Sequence[str], None] = '34a844edd2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
