"""model recipe

Revision ID: 62f979e9c97b
Revises: 4d948f3152ce
Create Date: 2026-07-22 13:38:39.585994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f979e9c97b'
down_revision: Union[str, Sequence[str], None] = '4d948f3152ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ingredients')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=32), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ingredients',
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('measurement_unit', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('is_subscribed', sa.BOOLEAN(), nullable=False),
    sa.Column('avatar', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
